version: '2.29.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true
    networks:
      - orders-dashboard-network

networks:
  orders-dashboard-network:
    driver: bridge